#!/usr/bin/env python3
"""Generate deterministic pseudo-prose without requiring the tokenizer.

The output target is approximately 140,000 characters. Harness clients load
the pinned tokenizer and take exact token-counted prefix slices at runtime.
"""

from __future__ import annotations

import argparse
import random
import sys
from pathlib import Path


SEED = 42
TARGET_CHARS = 200_000
ADJECTIVES = (
    "amber", "ancient", "brisk", "calm", "cobalt", "distant", "eager",
    "faint", "gentle", "granite", "hidden", "lively", "lucid", "mellow",
    "nimble", "patient", "quiet", "radiant", "silver", "steady", "subtle",
    "tender", "verdant", "vivid", "warm", "windy",
)
NOUNS = (
    "archive", "beacon", "bridge", "canyon", "citadel", "compass", "delta",
    "engine", "forest", "garden", "harbor", "horizon", "island", "lantern",
    "library", "meadow", "observatory", "orchard", "pathway", "quarry",
    "river", "signal", "station", "summit", "valley", "workshop",
)
VERBS = (
    "aligns", "balances", "carries", "charts", "collects", "connects",
    "crosses", "examines", "follows", "frames", "guides", "illuminates",
    "measures", "observes", "preserves", "records", "reveals", "shapes",
    "studies", "traces", "transforms", "visits", "weaves",
)
ADVERBS = (
    "carefully", "clearly", "deliberately", "evenly", "gently", "patiently",
    "precisely", "quietly", "steadily", "thoughtfully", "warmly",
)
CONNECTORS = (
    "after dawn", "before evening", "beneath a clear sky", "during the survey",
    "near the boundary", "past the old marker", "through the changing season",
    "under soft light", "while the town rests", "with measured attention",
)
TEMPLATES = (
    "The {a1} {n1} {v1} the {a2} {n2} {adv}, {conn}.",
    "{conn_cap}, a {a1} {n1} {v1} each {n2} and {v2} the {a2} route {adv}.",
    "Every {n1} appears {a1} when the {n2} {v1} {adv}, yet the {a2} {n3} remains.",
    "Observers beside the {a1} {n1} {v1} a {a2} {n2} {conn}, then {v2} onward.",
    "A {a1} {n1} and a {a2} {n2} {v1} together {adv}; their record {v2} the {n3}.",
)


def generate_text() -> str:
    rng = random.Random(SEED)
    paragraphs: list[str] = []
    total = 0
    sentence_number = 0
    while total < TARGET_CHARS:
        sentences: list[str] = []
        for _ in range(rng.randint(5, 9)):
            sentence_number += 1
            connector = rng.choice(CONNECTORS)
            values = {
                "a1": rng.choice(ADJECTIVES),
                "a2": rng.choice(ADJECTIVES),
                "n1": rng.choice(NOUNS),
                "n2": rng.choice(NOUNS),
                "n3": rng.choice(NOUNS),
                "v1": rng.choice(VERBS),
                "v2": rng.choice(VERBS),
                "adv": rng.choice(ADVERBS),
                "conn": connector,
                "conn_cap": connector.capitalize(),
            }
            sentence = rng.choice(TEMPLATES).format(**values)
            # A monotonic marker prevents the generated stream from having a
            # repeated finite cycle, including cycles shorter than 1,000 tokens.
            sentences.append(f"Record {sentence_number:06d}: {sentence}")
        paragraph = " ".join(sentences)
        paragraphs.append(paragraph)
        total += len(paragraph) + 2
    return "\n\n".join(paragraphs) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with the existing output without writing",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).with_name("ctx-32k.txt"),
        help="output path (default: fixtures/ctx-32k.txt)",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    generated = generate_text().encode("utf-8")
    if args.check:
        try:
            existing = args.out.read_bytes()
        except OSError as error:
            print(f"gen_fixtures.py: cannot read {args.out}: {error}", file=sys.stderr)
            return 1
        if existing != generated:
            print(f"gen_fixtures.py: generated bytes differ from {args.out}", file=sys.stderr)
            return 1
        print(f"fixture matches ({len(generated)} bytes): {args.out}")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_bytes(generated)
    print(f"wrote {len(generated)} bytes: {args.out}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except OSError as error:
        print(f"gen_fixtures.py: {error}", file=sys.stderr)
        raise SystemExit(1)
